# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: none

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Kura Documenation
tagline: Site Tagline
author :
  name : David Woodard
  email : david.woodard@eurotech.com

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://eclipse.github.io/kura
baseurl : /kura

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['post', 'Posts']
]
